### PR TITLE
almost working Dockerfile

### PR DESCRIPTION
**Pull request by crashfrog**
It _almost_ works, there's some issues with some of the CPAN packages. But it's a start.

Related to [issue 88.](https://github.com/tseemann/nullarbor/issues/88)

### CODE REVIEW

**Comment by pansapiens** [comment]
Here's my (working) `Dockerfile` for nullarbor 2 - it basically uses the conda package now, with some post-install workarounds to make it work. Much like @crashfrog 's image it includes the Kraken (and Centrifuge) databases in one monster image - some users may prefer a leaner database-free image - the biocontainers image via bioconda can fulfil that purpose (once it's working).

https://gist.github.com/pansapiens/68e231429789444e8472079fcf81316e

**Comment by tseemann** [comment]
In conda now, should be easy.

**Comment by pansapiens** [comment]
So if people stumble upon this issue and are looking for a Docker image, the best bet is probably the BioContainers one automatically built from the BioConda package, eg https://quay.io/repository/biocontainers/nullarbor

**Comment by tseemann** [comment]
Sorry i took so long to get to this.
Nullarbor is now in bioconda, which should make things a lot easier.

**Pull request closed without merging**
